//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public int STT { get; set; }
        public int BillID { get; set; }
        public int ProductID { get; set; }
        public int ProductBasisPrice { get; set; }
        public int ProductPrice { get; set; }
        public int Unit { get; set; }
    }
}
